[package]
name = "tmt_core"
version = "0.1.0"
edition = "2021"
authors = ["jay3332"]

[dependencies]
bitflags = "1.3.1"
lazy_static = "1.4"
plist = "1.3"

[target.'cfg(target_os = "macos")'.dependencies]
four-char-code = "0.0.5"
libc = "0.2.133"
