name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  BIN_NAME: tmt

jobs:
  build:
    strategy:
      matrix:
        target: ['x86_64-apple-darwin', 'aarch64-apple-darwin', 'x86_64-unknown-linux-gnu']
        
        include:
          - target: 'x86_64-apple-darwin'
            os: 'macos'

          - target: 'aarch64-apple-darwin'
            os: 'macos'

          - target: 'x86_64-unknown-linux-gnu'
            os: 'ubuntu'
      
    runs-on: ${{ format('{0}-latest', matrix.os) }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set rust toolchain to nightly
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        targets: 'aarch64-apple-darwin'
    
    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --verbose --release --target ${{ matrix.target }}
    
    - name: Rename bin
      run: mv target/${{ matrix.target }}/release/${{ env.BIN_NAME }}${{ matrix.ext }} ${{ env.BIN_NAME }}-${{ matrix.target }}${{ matrix.ext }}
    
    - uses: actions/upload-artifact@v3
      with:
        name: bin
        path: ${{ env.BIN_NAME }}-${{ matrix.target }}${{ matrix.ext }}
