name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  BIN_NAME: tmt

jobs:
  build:
    strategy:
      matrix:
        target: ['x86_64-apple-darwin', 'aarch64-apple-darwin', 'x86_64-unknown-linux-gnu']
        
        include:
          - target: 'x86_64-apple-darwin'
            os: 'macos'

          - target: 'aarch64-apple-darwin'
            os: 'macos'

          - target: 'x86_64-unknown-linux-gnu'
            os: 'ubuntu'
      
    runs-on: ${{ format('{0}-latest', matrix.os) }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set rust toolchain to nightly
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        targets: 'aarch64-apple-darwin'
    
    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --verbose --release --target ${{ matrix.target }}
    
    - name: Rename bin
      run: mv target/${{ matrix.target }}/release/${{ env.BIN_NAME }}${{ matrix.ext }} ${{ env.BIN_NAME }}-${{ matrix.target }}${{ matrix.ext }}
    
    - uses: actions/upload-artifact@v3
      with:
        name: bin
        path: ${{ env.BIN_NAME }}-${{ matrix.target }}${{ matrix.ext }}

  website:
    needs: [build]
    if: "success() && github.ref == 'refs/heads/main'"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: get wheelhouse artifacts
      uses: actions/download-artifact@v2
      with:
        name: bin
        path: bin
    
    - run: mv bin site/

    - name: Run template
      run: python .github/workflows/scripts/site_template.py

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./site

  deploy_website:
    needs: [website]

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
